fix webroot meaning

diff --git a/certify b/certify
--- a/certify
+++ b/certify
@@ -18,5 +18,21 @@ if [ -n "$email" ]; then
 	emailArg="--email $email"
 fi
 
+echo "Where is the webroot? A directory where certbot stores the token sent by Let's Encrypt and which will be served as a specified path by a web server running on port 80"
+read webroot
+if [ -z "$webroot" ] && ! [ -d "$webroot" ]; then
+	redecho "Invalid input! Either provided an invalid string or the specified directory does not exist"
+	exit 1
+fi
+
 # modify that line as you like and as required to fit your setup
-certbot certonly --webroot "$letsencryptDirHost" $emailArg $domain --rsa-key-size 4096 --agree-tos #--force-renewal"
+orangeecho "certbot certonly --webroot \"$webroot\" --config-dir \"$letsencryptDirHost\" -d \"$domain\" $emailArg --rsa-key-size 4096 --agree-to"
+echo "Continue executing this [yes|no]:"
+read x
+if ! [ "$x" = "yes" ]; then
+	echo "Aborting ..."
+	exit 0
+fi
+
+# modify that line as you like and as required to fit your setup
+certbot certonly --webroot "$webroot" --config-dir "$letsencryptDirHost" -d "$domain" $emailArg --rsa-key-size 4096 --agree-tos #--force-renewal"
