$city --> $mandant

diff --git a/workon b/workon
--- a/workon
+++ b/workon
@@ -11,14 +11,21 @@ orangeecho() {
 	echo -e "\033[1;33m$1\033[0;m"
 }
 
+normalizeToMandantVariable() {
+	## $city --> $mandant code guardening without breaking things. If $mandant hasn't been populated then
+	if [ -z "$mandant" ]; then
+		mandant="${city}" # try $city instead
+	fi
+}
+
 orangeecho "This script has been deprecated and will be removed in the next major release v3.0.0"
 
-workon_requiredvariables=( "city" "otpversion" "domain" )
+workon_requiredvariables=( "city" "mandant" "otpversion" "domain" )
 workon_optionalvariables=( "email" )
 
 if [ -z "$envfile" ] && [ -z "$1" ]; then
-	redecho "No city file to load found. \033[0;mExecute '\033[0;34m. ./workon <name of env file>\033[0;m'"
-	echo "List of available city files:"
+	redecho "No mandant file to load found. \033[0;mExecute '\033[0;34m. ./workon <name of env file>\033[0;m'"
+	echo "List of available mandant files:"
 	ls config
 	return
 fi
@@ -30,14 +37,14 @@ fi
 
 if ! [ -z "$1" ]; then
 	name=${1//".env"/""}
-	export cityfile="./config/$name.env"
+	export mandantFile="./config/$name.env"
 fi
 
 errors=""
-if ! [ -z "$cityfile" ]; then
-	orangeecho "importing variables from city configuration '$cityfile' (only the whitelisted ones) ..."
+if ! [ -z "$mandantFile" ]; then
+	orangeecho "importing variables from mandant configuration '$mandantFile' (only the whitelisted ones) ..."
 	# get all variables in a line string
-	variables=`cat $cityfile | xargs`
+	variables=`cat $mandantFile | xargs`
 	
 	# replace whitespaces with UNIX new line (needed by grep to get one variable with its content back at a time)
 	variables=`echo "$variables" | tr " " "\n"`
@@ -45,7 +52,7 @@ if ! [ -z "$cityfile" ]; then
 	for key in ${workon_requiredvariables[@]}; do
 		singlevar=`echo "$variables" | grep $key`
 		if [ -z "$singlevar" ]; then
-			echo -e "\033[0;33mWARNING:\033[0;m Environment variable '$key' is missing but mandatory. Some things will not work correctly. Repair the cityfile at '$cityfile' and execute this script again to fix!"
+			echo -e "\033[0;33mWARNING:\033[0;m Environment variable '$key' is missing but mandatory. Some things will not work correctly. Repair the mandant configuration at '$mandantFile' and execute this script again to fix!"
 			errors="yes"
 		else
 			export $singlevar
@@ -58,6 +65,8 @@ if ! [ -z "$cityfile" ]; then
 			export $singlevar
 		fi
 	done
+
+	normalizeToMandantVariable
 fi
 
 orangeecho "modifying prompt ..."
@@ -74,7 +83,7 @@ export PS1=\"$defaultPS1\";
 echo -e \"\033[1;33mRemoving environment variables previously set by this script ...\033[0;m\" ;
 for key in \${workon_requiredvariables[@]}; do export -n \$key ; done ;
 for key in \${workon_optionalvariables[@]}; do export -n \$key ; done ;
-export -n cityfile ;
+export -n mandantFile ;
 echo -e \"\033[1;33mRemoving command aliases ...\033[0;m\" ;
 unalias add ;
 unalias remove ;
